CREATE TABLE [dbo].[UsersUserTypes]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserID] NVARCHAR(128) FOREIGN KEY REFERENCES Users(AuthUserID),
	[UserTypeID] INT FOREIGN KEY REFERENCES UserTypes(ID)
)
