CREATE TABLE [dbo].[Users]
(
	[AuthUserID] NVARCHAR(128) NOT NULL PRIMARY KEY,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL, 
	[UserName] NVARCHAR(50) NOT NULL UNIQUE, 
	[TCIDNumber] VARCHAR(11) NOT NULL UNIQUE, 
	[PhoneNumber] VARCHAR(10) NOT NULL UNIQUE, 
	[EmailAddress] VARCHAR(255) NOT NULL UNIQUE,
	[Address] NVARCHAR(MAX) NOT NULL,

)
