CREATE TABLE [dbo].[Users]
(
	Id NVARCHAR(128) NOT NULL PRIMARY KEY,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL, 
	[TCIDNumber] VARCHAR(11) NOT NULL Unique, 
	[PhoneNumber] VARCHAR(10) NOT NULL, 
	[Address] NVARCHAR(MAX) NOT NULL,

)
