CREATE PROCEDURE [dbo].[spUpsertItem]
@UserID nvarchar(128),
@ItemTypeId int,
@Amount int
AS
	MERGE INTO UserItems AS TARGET
	USING
	(
		SELECT 
			@UserId [ID],
			@ItemtypeId [ITEMTYPEID],
			@Amount [AMOUNT]
	) AS SOURCE
	ON SOURCE.ID = TARGET.UserId and SOURCE.ITEMTYPEID = TARGET.ITEMTYPEID
	WHEN MATCHED
	THEN
		UPDATE SET
		TARGET.Amount = TARGET.Amount + SOURCE.AMOUNT
	WHEN NOT MATCHED BY TARGET THEN
	INSERT (UserId,ItemTypeId,Amount)
	VALUES (SOURCE.ID,SOURCE.ITEMTYPEID,SOURCE.AMOUNT);
